[package]
name = "bevy_bsml"
description = "Bevy UI library inspired by svelte and tailwindcss"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12" }
derive_more = "0.99.17"
